server:
  port: 8081

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Qq1995912Qq.com
    url: jdbc:mysql://master:3306/folder_monitor?userSSL=true
    type: com.alibaba.druid.pool.DruidDataSource
folder:
  config-path: paths.txt